### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jeremyfa** [snowkit/atom-flow#5]
1. Open the "Flow : set target" menu from CTRL + SHIFT + P
2. Type any letter to filter the list of target (for instance `w`)

![capture d ecran 2015-03-30 a 18 08 01](https://cloud.githubusercontent.com/assets/164094/6900633/219c7c5a-d708-11e4-8465-145bfd59d540.png)

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [flow](https://github.com/snowkit/atom-flow) package, v0.4.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/jeremyfa/Documents/Projets/atom-flow/node_modules/atom-space-pen-views/node_modules/fuzzaldrin/lib/scorer.js:60

TypeError: undefined is not a function
  at Object.exports.score (/Users/jeremyfa/Documents/Projets/atom-flow/node_modules/atom-space-pen-views/node_modules/fuzzaldrin/lib/scorer.js:60:31)
  at module.exports (/Users/jeremyfa/Documents/Projets/atom-flow/node_modules/atom-space-pen-views/node_modules/fuzzaldrin/lib/filter.js:25:24)
  at module.exports.filter (/Users/jeremyfa/Documents/Projets/atom-flow/node_modules/atom-space-pen-views/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
  at FlowStatus.module.exports.SelectListView.populateList (/Users/jeremyfa/Documents/Projets/atom-flow/node_modules/atom-space-pen-views/lib/select-list-view.js:195:25)
  at /Users/jeremyfa/Documents/Projets/atom-flow/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26

```
### Commands

```
  5x -0:14.9 core:backspace (atom-text-editor.editor)
     -0:07.3 core:save (atom-text-editor.editor)
     -0:05.9 command-palette:toggle (atom-text-editor.editor)
     -0:03.2 core:move-down (atom-text-editor.editor.mini)
     -0:02.9 core:confirm (atom-text-editor.editor.mini)
     -0:02.9 flow:set-target (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".*.hx",
      ".DS_Store"
    ]
  },
  "flow": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v0.6.2
autocomplete-plus, v2.7.0
flow, v0.4.0
haxe, v0.6.0
jsformat, v0.7.18
language-ect, v0.2.0
language-haxe, v0.2.1
language-typescript, v0.15.0
linter, v0.12.0
monokai, v0.13.0

# Dev
No dev packages
```

**Comment by ruby0x1** [comment]
thanks, I've run into this but wasn't sure where it's triggered by specifically yet

**Comment by ruby0x1** [comment]
see #9 , this should be fixed
