### ISSUE TITLE
Failed to activate the flow package

### ISSUE THREAD

**Issue by Khaledgarbaya** [snowkit/atom-flow#8]
[Enter steps to reproduce below:]
1. Update to Atom 1.03
2. Update atom-flow

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [flow](https://github.com/snowkit/atom-flow) package, v0.4.1
### Stack Trace

Failed to activate the flow package

```
At Can't register a command with non-function callback.

Error: Can't register a command with non-function callback.
    at CommandRegistry.module.exports.CommandRegistry.add (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:44:15)
    at Object.module.exports._command (/Users/username/.atom/packages/flow/lib/flow.js:209:33)
    at Object.module.exports._init_internal (/Users/username/.atom/packages/flow/lib/flow.js:196:14)
    at Object.module.exports.activate (/Users/username/.atom/packages/flow/lib/flow.js:27:14)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:453:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:312:60
```
### Commands

```
     -0:22.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-atom-material-ui)
```
### Config

``` json
{
  "core": {
   ....
    "disabledPackages": [
      "language-actionscript3",
      "language-actionscript3",
      "language-actionscript3",
      "autocomplete-haxe"
    ]
  },
  "flow": {}
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.9
flow, v0.4.1
haxe, v0.8.4
language-haxe, v0.3.0
language-protobuf, v0.5.0
linter, v1.2.4
minimap, v4.12.1
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by ruby0x1** [comment]
Does it throw this error after restarting? I'm curious because the code looks sound and doesn't error here (OSX 10.10.x, Atom  1.0.3)

**Comment by Khaledgarbaya** [comment]
No issue after restarting .
I had atom 1.0.2 and then I updated to 1.0.3, after finishing the update the atom-flow asks for update and then this crash happened.
Maybe there is 1 in 1000 this will happen .
I will close the issue since everything is working after restarting maybe something was wrong with my system

Best,
Khaled

**Comment by ruby0x1** [comment]
Thanks for reporting back. It sounds like because the plugin may have been running it kept a copy alive, somewhere in a cache maybe. But glad it's working!
