### ISSUE TITLE
Uncaught TypeError: string.indexOf is not a function

### ISSUE THREAD

**Issue by prime31** [snowkit/atom-flow#9]
[Enter steps to reproduce below:]
1. Cmd+shift+p to open the command palette
2. type "flow set" and press enter to open the target selector
3. start typing and the exception gets thrown

**Atom Version**: 1.0.15
**System**: Mac OS X 10.11
**Thrown From**: [flow](https://github.com/snowkit/atom-flow) package, v0.4.3
### Stack Trace

Uncaught TypeError: string.indexOf is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzaldrin/lib/scorer.js:60

TypeError: string.indexOf is not a function
  at Object.exports.score (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzaldrin/lib/scorer.js:60:31)
  at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzaldrin/lib/filter.js:25:24)
  at module.exports.filter (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
  at FlowStatus.module.exports.SelectListView.populateList (/Users/desaro/.atom/packages/flow/node_modules/atom-space-pen-views/lib/select-list-view.js:195:25)
  at /Users/desaro/.atom/packages/flow/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26

```
### Commands

```
  5x -1:42 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -1:40.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:34.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -1:32.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:30.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:28.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:28.8.0 haxe:clear-project (atom-text-editor.editor)
     -1:26.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -1:23.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:27.4.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:24.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.2.0 flow:status (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "*.meta",
      ".meta"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-fix-path, v0.1.0
flow, v0.4.3
haxe, v0.8.7
language-c, v0.48.0
language-haxe, v0.3.0
linter, v1.6.0

# Dev
No dev packages
```

**Comment by prime31** [comment]
This can be fixed by making the following modification to the flow-status.js file. It just needs to tell the list view which property to filter the typing on. Add the following code after the FlowStatus.prototype.viewForItem method:

```
FlowStatus.prototype.getFilterKey = function() {
    return 'text';
}
```
